# Generated by Django 4.1.3 on 2022-12-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='Status',
            field=models.CharField(choices=[('not committed', 'not committed'), ('committed', 'committed')], default='not committed', max_length=20),
        ),
    ]
